# end-to-end data is just placeholder code
exclude: tests/end_to_end/data
repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-pep604,flake8-no-pep420]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black.git
    rev: 24.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/matthewhughes934/py-unused-deps
    rev: v0.4.2
    hooks:
    -   id: py-unused-deps
        args:
          - "--distribution"
          - "py-unused-deps"
          - "unused_deps"
-   repo: "https://github.com/matthewhughes934/pre-commit-format-markdown"
    rev: v0.5.0
    hooks:
    -   id: format-markdown-docker
-   repo: https://gitlab.com/matthewhughes/common-changelog
    rev: v0.2.0
    hooks:
    -   id: validate-changelog
