# end-to-end data is just placeholder code
exclude: tests/end_to_end/data
repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-pep604,flake8-no-pep420]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black.git
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/matthewhughes934/py-unused-deps
    rev: bb14d7715ee30db3d69ffbab2f2544e3ea55ec3a
    hooks:
    -   id: py-unused-deps
        args:
          - "--distribution"
          - "py-unused-deps"
          - "unused_deps"
-   repo: "https://github.com/matthewhughes934/pre-commit-format-markdown"
    rev: v0.5.0
    hooks:
    -   id: format-markdown-docker
