# end-to-end date is just placeholder code
exclude: tests/end_to_end/data
repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-pep604,flake8-no-pep420]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/isort.git
    rev: v5.11.3
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black.git
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
