repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-pep604,flake8-no-pep420]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.981
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black.git
    rev: 22.8.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
