-   id: py-unused-deps
    name: py-unused-deps
    description: Find unused Python dependencies
    entry: py-unused-deps
    language: system
    always_run: true
    args:
      - "--no-distribution"
