version: 2.1
orbs:
  python: circleci/python@2.0.3

definitions:
  install-args: &install-args
      pkg-manager: pip-dist
      pip-dependency-file: requirements-dev.txt
      args: --requirement requirements-dev.txt

jobs:
  lint:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages: *install-args
      - run:
          command: |
            cp .pre-commit-config.yaml pre-commit-cache-key.txt
            python --version --version >> pre-commit-cache-key.txt
      - restore_cache:
          key: v1-pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
      - run: pre-commit run --all-files --show-diff-on-failure
      - save_cache:
          key: v1-pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
          paths:
            - ~/.cache/pre-commit
  unit-tests:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/python:<< parameters.version >>
    steps:
      - checkout
      - python/install-packages: *install-args
      - run:
          name: Run unit tests
          command: coverage run --module pytest
      - run: coverage report

  end-to-end-tests:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/python:<< parameters.version >>
    steps:
      - checkout
      - python/install-packages: *install-args
      - run:
          name: Install mock dependencies
          command: |
            # To keep things simple, don't bother installing virtualenvs
            poetry config virtualenvs.create false
            tests/end_to_end/data/install_all.sh
      - run:
          name: Run end-to-end tests
          command: pytest tests/end_to_end

  self-run:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages: *install-args
      - run: py-unused-deps --distribution py-unused-deps unused_deps

workflows:
  test-and-lint:
    jobs:
      - unit-tests:
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      - end-to-end-tests:
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      - lint
      - self-run
